//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MyNotesReadModelModel", "FK__ItemStock__Item__2ED0D4B0", "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ReadModel.Item), "ItemStock", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReadModel.ItemStock), true)]
[assembly: EdmRelationshipAttribute("MyNotesReadModelModel", "FK__pickListI__pickL__2A0C1F93", "picklist", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ReadModel.picklist), "pickListItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ReadModel.pickListItem), true)]

#endregion

namespace ReadModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MyNotesReadModelEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MyNotesReadModelEntities object using the connection string found in the 'MyNotesReadModelEntities' section of the application configuration file.
        /// </summary>
        public MyNotesReadModelEntities() : base("name=MyNotesReadModelEntities", "MyNotesReadModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyNotesReadModelEntities object.
        /// </summary>
        public MyNotesReadModelEntities(string connectionString) : base(connectionString, "MyNotesReadModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyNotesReadModelEntities object.
        /// </summary>
        public MyNotesReadModelEntities(EntityConnection connection) : base(connection, "MyNotesReadModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Items
        {
            get
            {
                if ((_Items == null))
                {
                    _Items = base.CreateObjectSet<Item>("Items");
                }
                return _Items;
            }
        }
        private ObjectSet<Item> _Items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemStock> ItemStocks
        {
            get
            {
                if ((_ItemStocks == null))
                {
                    _ItemStocks = base.CreateObjectSet<ItemStock>("ItemStocks");
                }
                return _ItemStocks;
            }
        }
        private ObjectSet<ItemStock> _ItemStocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<picklist> picklists
        {
            get
            {
                if ((_picklists == null))
                {
                    _picklists = base.CreateObjectSet<picklist>("picklists");
                }
                return _picklists;
            }
        }
        private ObjectSet<picklist> _picklists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pickListItem> pickListItems
        {
            get
            {
                if ((_pickListItems == null))
                {
                    _pickListItems = base.CreateObjectSet<pickListItem>("pickListItems");
                }
                return _pickListItems;
            }
        }
        private ObjectSet<pickListItem> _pickListItems;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemStocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemStocks(ItemStock itemStock)
        {
            base.AddObject("ItemStocks", itemStock);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the picklists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopicklists(picklist picklist)
        {
            base.AddObject("picklists", picklist);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pickListItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopickListItems(pickListItem pickListItem)
        {
            base.AddObject("pickListItems", pickListItem);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyNotesReadModelModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="item1">Initial value of the Item1 property.</param>
        public static Item CreateItem(global::System.Guid item1)
        {
            Item item = new Item();
            item.Item1 = item1;
            return item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Item1
        {
            get
            {
                return _Item1;
            }
            set
            {
                if (_Item1 != value)
                {
                    OnItem1Changing(value);
                    ReportPropertyChanging("Item1");
                    _Item1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Item1");
                    OnItem1Changed();
                }
            }
        }
        private global::System.Guid _Item1;
        partial void OnItem1Changing(global::System.Guid value);
        partial void OnItem1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Qty
        {
            get
            {
                return _Qty;
            }
            set
            {
                OnQtyChanging(value);
                ReportPropertyChanging("Qty");
                _Qty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Qty");
                OnQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _Qty;
        partial void OnQtyChanging(Nullable<global::System.Int32> value);
        partial void OnQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyNotesReadModelModel", "FK__ItemStock__Item__2ED0D4B0", "ItemStock")]
        public EntityCollection<ItemStock> ItemStocks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemStock>("MyNotesReadModelModel.FK__ItemStock__Item__2ED0D4B0", "ItemStock");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemStock>("MyNotesReadModelModel.FK__ItemStock__Item__2ED0D4B0", "ItemStock", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyNotesReadModelModel", Name="ItemStock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemStock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemStock object.
        /// </summary>
        /// <param name="itemStockId">Initial value of the ItemStockId property.</param>
        public static ItemStock CreateItemStock(global::System.Guid itemStockId)
        {
            ItemStock itemStock = new ItemStock();
            itemStock.ItemStockId = itemStockId;
            return itemStock;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ItemStockId
        {
            get
            {
                return _ItemStockId;
            }
            set
            {
                if (_ItemStockId != value)
                {
                    OnItemStockIdChanging(value);
                    ReportPropertyChanging("ItemStockId");
                    _ItemStockId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemStockId");
                    OnItemStockIdChanged();
                }
            }
        }
        private global::System.Guid _ItemStockId;
        partial void OnItemStockIdChanging(global::System.Guid value);
        partial void OnItemStockIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> Item
        {
            get
            {
                return _Item;
            }
            set
            {
                OnItemChanging(value);
                ReportPropertyChanging("Item");
                _Item = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Item");
                OnItemChanged();
            }
        }
        private Nullable<global::System.Guid> _Item;
        partial void OnItemChanging(Nullable<global::System.Guid> value);
        partial void OnItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Qty
        {
            get
            {
                return _Qty;
            }
            set
            {
                OnQtyChanging(value);
                ReportPropertyChanging("Qty");
                _Qty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Qty");
                OnQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _Qty;
        partial void OnQtyChanging(Nullable<global::System.Int32> value);
        partial void OnQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> RefId
        {
            get
            {
                return _RefId;
            }
            set
            {
                OnRefIdChanging(value);
                ReportPropertyChanging("RefId");
                _RefId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RefId");
                OnRefIdChanged();
            }
        }
        private Nullable<global::System.Guid> _RefId;
        partial void OnRefIdChanging(Nullable<global::System.Guid> value);
        partial void OnRefIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyNotesReadModelModel", "FK__ItemStock__Item__2ED0D4B0", "Item")]
        public Item Item1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("MyNotesReadModelModel.FK__ItemStock__Item__2ED0D4B0", "Item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("MyNotesReadModelModel.FK__ItemStock__Item__2ED0D4B0", "Item").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Item> Item1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("MyNotesReadModelModel.FK__ItemStock__Item__2ED0D4B0", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Item>("MyNotesReadModelModel.FK__ItemStock__Item__2ED0D4B0", "Item", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyNotesReadModelModel", Name="picklist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class picklist : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new picklist object.
        /// </summary>
        /// <param name="pickListId">Initial value of the PickListId property.</param>
        public static picklist Createpicklist(global::System.Guid pickListId)
        {
            picklist picklist = new picklist();
            picklist.PickListId = pickListId;
            return picklist;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PickListId
        {
            get
            {
                return _PickListId;
            }
            set
            {
                if (_PickListId != value)
                {
                    OnPickListIdChanging(value);
                    ReportPropertyChanging("PickListId");
                    _PickListId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PickListId");
                    OnPickListIdChanged();
                }
            }
        }
        private global::System.Guid _PickListId;
        partial void OnPickListIdChanging(global::System.Guid value);
        partial void OnPickListIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _Number;
        partial void OnNumberChanging(Nullable<global::System.Int32> value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Customer
        {
            get
            {
                return _Customer;
            }
            set
            {
                OnCustomerChanging(value);
                ReportPropertyChanging("Customer");
                _Customer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Customer");
                OnCustomerChanged();
            }
        }
        private global::System.String _Customer;
        partial void OnCustomerChanging(global::System.String value);
        partial void OnCustomerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyNotesReadModelModel", "FK__pickListI__pickL__2A0C1F93", "pickListItem")]
        public EntityCollection<pickListItem> pickListItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<pickListItem>("MyNotesReadModelModel.FK__pickListI__pickL__2A0C1F93", "pickListItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<pickListItem>("MyNotesReadModelModel.FK__pickListI__pickL__2A0C1F93", "pickListItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyNotesReadModelModel", Name="pickListItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pickListItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pickListItem object.
        /// </summary>
        /// <param name="pickListItemId">Initial value of the PickListItemId property.</param>
        public static pickListItem CreatepickListItem(global::System.Guid pickListItemId)
        {
            pickListItem pickListItem = new pickListItem();
            pickListItem.PickListItemId = pickListItemId;
            return pickListItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PickListItemId
        {
            get
            {
                return _PickListItemId;
            }
            set
            {
                if (_PickListItemId != value)
                {
                    OnPickListItemIdChanging(value);
                    ReportPropertyChanging("PickListItemId");
                    _PickListItemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PickListItemId");
                    OnPickListItemIdChanged();
                }
            }
        }
        private global::System.Guid _PickListItemId;
        partial void OnPickListItemIdChanging(global::System.Guid value);
        partial void OnPickListItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> pickListId
        {
            get
            {
                return _pickListId;
            }
            set
            {
                OnpickListIdChanging(value);
                ReportPropertyChanging("pickListId");
                _pickListId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pickListId");
                OnpickListIdChanged();
            }
        }
        private Nullable<global::System.Guid> _pickListId;
        partial void OnpickListIdChanging(Nullable<global::System.Guid> value);
        partial void OnpickListIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> Item
        {
            get
            {
                return _Item;
            }
            set
            {
                OnItemChanging(value);
                ReportPropertyChanging("Item");
                _Item = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Item");
                OnItemChanged();
            }
        }
        private Nullable<global::System.Guid> _Item;
        partial void OnItemChanging(Nullable<global::System.Guid> value);
        partial void OnItemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Qty
        {
            get
            {
                return _Qty;
            }
            set
            {
                OnQtyChanging(value);
                ReportPropertyChanging("Qty");
                _Qty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Qty");
                OnQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _Qty;
        partial void OnQtyChanging(Nullable<global::System.Int32> value);
        partial void OnQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MyNotesReadModelModel", "FK__pickListI__pickL__2A0C1F93", "picklist")]
        public picklist picklist
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<picklist>("MyNotesReadModelModel.FK__pickListI__pickL__2A0C1F93", "picklist").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<picklist>("MyNotesReadModelModel.FK__pickListI__pickL__2A0C1F93", "picklist").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<picklist> picklistReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<picklist>("MyNotesReadModelModel.FK__pickListI__pickL__2A0C1F93", "picklist");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<picklist>("MyNotesReadModelModel.FK__pickListI__pickL__2A0C1F93", "picklist", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
